import Link from "next/link";

import GraphGroup from "@/components/DataGraph/GraphGroup";
import Button from "@/components/Form/Button";
import moneyimage from "@/public/images/moneyimage.png";

export default function Home() {
  const sales = [
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Sep", amount: 5000 },
    { month: "Sep", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Oct", amount: 5000 },
    { month: "Oct", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Nov", amount: 5000 },
    { month: "Nov", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Dec", amount: 2100 },
    { month: "Dec", amount: 5000 },
    { month: "Dec", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
    { month: "Jan", amount: 2100 },
    { month: "Jan", amount: 5000 },
    { month: "Jan", amount: 2500 },
    { month: "Feb", amount: 2100 },
    { month: "Feb", amount: 5000 },
    { month: "Feb", amount: 2500 },
  ];

  return (
    <main className="flex h-screen">
      <div className="flex flex-1 items-center justify-center">
        <div className="ml-16 w-[80%]">
          <h1 className="w-[80%] text-6xl font-bold">
            <span className="text-customGreen01">Track</span>,
            <span className="text-customGreen01">Manage</span>, and
            <span className="text-customGreen01"> Grow</span> your Business with
            <span className="text-customGreen01"> Precision.</span>
          </h1>
          <div className="mt-4 flex w-[40%]">
            <div className="mr-8">
              <Button invert={true}>
                <Link href="/rates">See Rates</Link>
              </Button>
            </div>
            <div>
              <Button invert={true}>
                <Link href="/login">Login</Link>
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-1 items-center justify-center">
        <div className="w-[60%]">
          <img src="/images/moneyimage.png" />
        </div>
      </div>
    </main>
  );
}
