"use client";

const sales = [
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Sep", amount: 5000 },
  { month: "Sep", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Oct", amount: 5000 },
  { month: "Oct", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Nov", amount: 5000 },
  { month: "Nov", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Dec", amount: 2100 },
  { month: "Dec", amount: 5000 },
  { month: "Dec", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
  { month: "Jan", amount: 2100 },
  { month: "Jan", amount: 5000 },
  { month: "Jan", amount: 2500 },
  { month: "Feb", amount: 2100 },
  { month: "Feb", amount: 5000 },
  { month: "Feb", amount: 2500 },
];

import { useQuery } from "@tanstack/react-query";

import Spinner from "@/components/Indicators/Spinner";
import ErrorIndicator from "@/components/Indicators/Error";
import OwnerDashboard from "@/components/Dashboard/Owner/OwnerDashboard";
import CashierDashBoard from "@/components/Dashboard/Cashier/CashierDashboard";
import WorkerDashboard from "@/components/Dashboard/Worker/WorkerDashboard";

export default function Dashboard({ params }) {
  const { accountID } = params;

  const { data, error, isError, isLoading } = useQuery({
    queryKey: ["role", accountID],
    queryFn: async () => {
      const response = await fetch(`/api/${accountID}/dashboard`);
      if (!response.ok) {
        throw new Error("There is an error occurred.");
      }
      return await response.json();
    },
  });

  let content;
  if (isLoading) {
    content = <Spinner />;
  } else if (isError) {
    content = <ErrorIndicator message={error.message} />;
  } else if (data?.role === "owner") {
    content = <OwnerDashboard id={accountID} sales={sales} />;
  } else if (data?.role === "cashier") {
    content = <CashierDashBoard />;
  } else if (data?.role === "worker") {
    content = <WorkerDashboard />;
  } else {
    content = <h1>not recognized.</h1>;
  }

  return <main className="flex h-screen">{content}</main>;
}
